# Change these first
owner: functionalmetatable # Your GitHub username
repo: pingr # Your GitHub repository name

# Add your sites here
sites:
  - name: replit pinger
    url: https://pico.9gr.repl.co

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /pingr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "pingr"
  introMessage: uhhh why did i make this
  navbar:
    - title: pingr
      href: /
    - title: github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration 
